export function Disclaimer() {
  return (
    <p className="mx-auto max-w-3xl text-center text-xs text-neutral-500">
      This report is generated by AI using public weather and climate data. It is an
      informational planning aid, not professional engineering, financial, legal, or insurance
      advice. Risk levels are estimates and may not reflect conditions at your specific property.
      Always consult licensed professionals (structural engineers, insurance agents, contractors)
      before making significant financial or safety decisions.
    </p>
  );
}
